import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const base = process.env.GAME_BROWSER_URL || 'http://localhost:8787';
const browser = await chromium.launch({ headless: true });
const errors = [];
await mkdir('screenshots', { recursive: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
const page = await context.newPage();
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
await page.goto(base);
await page.screenshot({ path: 'screenshots/desktop-home.png', fullPage: true });
await page.locator('#player-name').fill('Sunny');
await page.locator('#play-solo').click();
await page.locator('.market-chart').waitFor();
await page.waitForFunction(() => document.querySelector('#connection').textContent === 'Connected');
await page.screenshot({ path: 'screenshots/desktop-game.png', fullPage: true });
assert.equal(await page.locator('.player-card').count(), 2);
await page.locator('[data-action="buy"]').click();
await page.locator('[data-quantity="3"]').click();
await page.waitForTimeout(500);
await page.locator('#lock-order').click();
await page.locator('#skip-reveal').waitFor();
await page.locator('#skip-reveal').click();
await page.locator('#lock-order:not([disabled])').waitFor();
await page.reload();
await page.locator('.market-chart').waitFor();
await page.waitForFunction(() => document.querySelector('#connection').textContent === 'Connected');
await page.locator('#language').click();
assert.equal(await page.locator('html').getAttribute('lang'), 'ko');
await page.locator('#rules-button').click();
assert.equal(await page.locator('#rules-dialog').evaluate(d => d.open), true);
await page.locator('#rules-done').click();
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'screenshots/mobile-game.png', fullPage: true });
for (const width of [320, 390, 768, 1440]) {
  await page.setViewportSize({ width, height: 900 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `Overflow at ${width}`);
}
// A second independent browser follows the friends-only journey.
const friends = await browser.newContext({ viewport: { width: 390, height: 844 } });
const host = await friends.newPage();
host.on('pageerror', error => errors.push(error.message));
await host.goto(base); await host.locator('#player-name').fill('Host'); await host.locator('#create-room').click();
await host.locator('.room-code').waitFor();
const code = await host.locator('.room-code').textContent();
const guestContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const guest = await guestContext.newPage();
guest.on('pageerror', error => errors.push(error.message));
await guest.goto(`${base}/?room=${code}`); await guest.locator('#player-name').fill('Guest'); await guest.locator('#join-room').click();
await guest.locator('#ready').waitFor(); await guest.locator('#ready').click();
await host.locator('#ready').click(); await host.locator('#start-game:not([disabled])').waitFor(); await host.locator('#start-game').click();
await host.locator('.market-chart').waitFor(); await guest.locator('.market-chart').waitFor();
await host.locator('#lock-order').click(); await guest.locator('#lock-order').click();
await guest.locator('#skip-reveal').waitFor();
assert.ok(await host.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Multiplayer mobile overflow');
await host.screenshot({ path: 'screenshots/mobile-multiplayer.png', fullPage: true });
assert.deepEqual(errors, []);
console.log(`PASS: ${base} — solo trade, refresh/reconnect, Korean, rules dialog, multiplayer UI and 320–1440px layouts; no browser errors`);
await browser.close();
