import { chromium } from "@playwright/test";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
const base = process.env.GAME_BROWSER_URL || "http://localhost:8787";
await mkdir("screenshots", { recursive: true });
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(base);
  await page.locator("#player-name").fill("Table tester");
  await page.locator("#solo-timer").selectOption("0");
  await page.locator("#play-solo").click();
  await page.locator("#lock-order:not([disabled])").waitFor();
  const bounds = () => page.evaluate(() => Object.fromEntries(["#table-market", "#table-news", "#table-trade"].map(selector => {
    const rect = document.querySelector(selector).getBoundingClientRect();
    return [selector, { x: rect.x, y: rect.y, width: rect.width, height: rect.height, bottom: rect.bottom }];
  })));
  const before = await bounds();
  for (const rect of Object.values(before)) assert.ok(rect.bottom <= 900, "All desktop panels fit the screen");
  assert.ok(before["#table-market"].x < before["#table-news"].x && before["#table-news"].x < before["#table-trade"].x);
  await page.locator("#lock-order").click();
  await page.locator("#next-round-control").waitFor();
  assert.deepEqual(await bounds(), before, "Panels stay fixed when the news appears");
  assert.equal(await page.locator(".table-dice").isVisible(), true);
  assert.equal(await page.locator("#round-details").getAttribute("open"), null);
  assert.equal(await page.locator(".newspaper-reason").isVisible(), true);
  assert.equal(await page.locator(".player-holdings b").count(), 8);
  assert.equal(await page.locator(".stock-tile .owned-shares").count(), 4);
  assert.match(await page.locator('[data-counter="price-coop"]').textContent(), /^\$/);
  await page.screenshot({ path: "screenshots/compact-table-desktop.png" });
  await page.locator("#expand-newspaper").click();
  await page.locator("#newspaper-dialog[open]").waitFor();
  assert.equal(await page.locator("#expanded-newspaper .newspaper-byline").isVisible(), true);
  assert.equal(await page.locator("#expanded-newspaper .newspaper-reason p").textContent(), await page.locator("#table-news .newspaper-reason p").textContent());
  assert.equal(await page.locator("#replay-news-sound").count(), 1, "Expanded paper has a distinct replay ID");
  await page.keyboard.press("Escape");
  assert.equal(await page.locator("#newspaper-dialog").getAttribute("open"), null);
  assert.equal(await page.evaluate(() => document.activeElement.id), "expand-newspaper");
  await page.locator("#next-round-control").click();
  await page.locator("#lock-order:not([disabled])").waitFor();
  assert.deepEqual(await bounds(), before, "Next planning round stays in place");
  await page.setViewportSize({ width: 1366, height: 768 });
  await page.screenshot({ path: "screenshots/compact-table-laptop.png" });
  for (const rect of Object.values(await bounds())) assert.ok(rect.bottom <= 768);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator("#tab-trade").click();
  await page.locator('[data-action="buy"]').click();
  await page.locator('[data-quantity="2"]').click();
  assert.equal(await page.locator("#table-market").isVisible(), false);
  await page.locator("#lock-order").click();
  await page.locator("#next-round-control").waitFor();
  assert.equal(await page.locator(".compact-table").getAttribute("data-table-pane"), "trade", "News never switches the tab automatically");
  assert.equal(await page.locator(".new-news-badge").isVisible(), true);
  assert.equal(await page.evaluate(() => scrollY), 0, "News never scrolls the page automatically");
  await page.locator("#tab-news").click();
  assert.equal(await page.locator(".new-news-badge").isVisible(), false);
  const visibility = await page.evaluate(() => {
    const panel = document.querySelector("#table-news").getBoundingClientRect();
    const reason = document.querySelector("#table-news .newspaper-reason").getBoundingClientRect();
    const tabs = document.querySelector(".table-tabs").getBoundingClientRect();
    return { reasonBottom: reason.bottom, panelBottom: panel.bottom, tabsTop: tabs.top };
  });
  assert.ok(visibility.reasonBottom <= visibility.panelBottom, "The story and reason fit the phone panel");
  assert.ok(visibility.panelBottom <= visibility.tabsTop, "Tabs do not cover the panel");
  await page.screenshot({ path: "screenshots/compact-table-phone-news.png" });
  await page.locator("#language").click();
  assert.equal(await page.locator(".compact-table").getAttribute("data-table-pane"), "news", "Language rerender preserves the selected pane");
  assert.match(await page.locator("#table-news .newspaper-masthead").textContent(), /꼬꼬일보/);
  await page.locator("#tab-news").focus();
  await page.keyboard.press("ArrowRight");
  assert.equal(await page.locator("#tab-trade").getAttribute("aria-selected"), "true");
  await page.locator("#language").click();
  if (await page.locator("#next-round-control").isVisible()) await page.locator("#next-round-control").click();
  await page.locator("#lock-order:not([disabled])").waitFor();
  await page.screenshot({ path: "screenshots/compact-table-phone-trade.png" });
  for (const width of [320, 375, 390, 768, 1024]) {
    await page.setViewportSize({ width, height: 844 });
    for (const pane of ["market", "news", "trade"]) {
      await page.locator(`#tab-${pane}`).click();
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${width}px in ${pane}`);
      assert.equal(await page.locator(`#table-${pane}`).isVisible(), true);
      assert.equal(await page.locator('.compact-table > .panel:visible').count(), 1);
    }
  }
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.waitForFunction(() => [...document.querySelectorAll(".compact-table > .panel")].every(panel => !panel.hidden));
  assert.equal(await page.locator('.compact-table > .panel:visible').count(), 3, "Desktop restores all panels after a mobile resize");
  await page.locator('[data-action="buy"]').click();
  await page.locator("#trade-stock").selectOption("coop");
  await page.locator("#protection-choice summary").click();
  await page.locator("#protection").selectOption("coop");
  await page.waitForFunction(() => document.querySelector("#draft-status").textContent.startsWith("SAVED"));
  const protectedBounds = await bounds();
  await page.locator("#lock-order").click();
  await page.locator("#next-round-control").waitFor();
  assert.deepEqual(await bounds(), protectedBounds, "Expanded protection does not move the main panels");
  await page.locator("#round-details summary").click();
  assert.equal(await page.locator(".price-equation").count(), 4);
  assert.equal(await page.locator(".reveal-dice").isVisible(), true);
  await page.locator("#next-round-control").click();
  await page.locator("#lock-order:not([disabled])").waitFor();
  assert.deepEqual(await bounds(), protectedBounds);
  assert.deepEqual(errors, []);
  console.log("PASS: desktop table fits, stable round phases, phone tabs, unread news, keyboard navigation, expanded paper and responsive widths.");
} finally { await browser.close(); }
